### ISSUE TITLE
Can't deploy local version

### ISSUE THREAD

**Issue by guitarhero1** [smyalko/bot_durova#3]
My hardware:  
CPU: Pentium-60.
RAM: 8MB RAM.
GPU: SVGA Video Card.
OS: Windows 95.
ODD: Double Speed CD-ROM

Excuse me, I can't launch it on hardware above. Please, add supporting for this...

**Comment by smyalko** [comment]
Hmm, you need to install at least Windows XP and 1 GB RAM to deploy self-contained application currently. We will add low-cost computers support in future, but now try to use [Microsoft Azure cloud](https://azure.microsoft.com/)

**Comment by guitarhero1** [comment]
Hm, I've never still heard about clouds... Thanks, I'll try.
